name: rental_manager
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_storage:
  email_validator: "^1.0.0"
  intl: ^0.16.0
  font_awesome_flutter: ^8.2.0
  image_picker: ^0.5.3+1
  progress_dialog: ^1.2.1
  google_sign_in: ^4.1.1
  awesome_dialog: ^0.1.3
  pull_to_refresh: ^1.5.7
  liquid_pull_to_refresh: ^1.1.1
  image_cropper: ^1.2.1
  flutter_reactive_button: ^1.1.0
  flutter_beautiful_popup: ^1.5.0
  giffy_dialog: ^1.7.0
  draggable_fab: ^0.1.1
  flutter_speed_dial: ^1.2.5
  slide_popup_dialog: ^0.0.2
  firebase_database: ^3.1.3
  shared_preferences: ^0.5.6+2
  fluttertoast: ^3.1.3
  photo_view: ^0.9.2
  firebase_messaging: ^6.0.12
  flutter_local_notifications: ^1.2.0+4
  flutter_signin_button: ^1.0.0
  path_provider: ^1.6.5
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
  mailer: ^3.0.4
  cached_network_image: ^2.0.0
  grouped_buttons: ^1.0.4
  flutter_ticket_widget: ^0.0.1
  wc_flutter_share: ^0.2.0
  geolocator: ^5.3.0
  google_maps_flutter: ^0.5.25+2
  flutter_polyline_points: ^0.1.0
  google_map_polyline: ^0.2.0+1
  http: ^0.12.0+4
  file_picker: ^1.6.1
  flappy_search_bar: 1.4.1
  percent_indicator: ^2.1.3
  flutter_rating_bar: ^3.0.1+1
  devicelocale: ^0.2.3
  validators: ^2.0.0+1
  numberpicker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
